### ISSUE TITLE
let-flow within loop blocks forever

### ISSUE THREAD

**Issue by kennyjwilli** [aleph-io/manifold#187]
Running the below code will block the thread forever. The [docs on deferred](https://github.com/ztellman/manifold/blob/b7183ce2f63a311f10e433dafd2df782542d1140/docs/deferred.md#manifolddeferredloop) say "the combination of loop and let-flow can allow for the specification of highly intricate asynchronous workflows". That seems to imply that the below code should work. 

```clojure
(require '[manifold.deferred :as deferred])
(require '[aleph.http :as http])

(defn request-example
  [request-map]
  (deferred/loop
    []
    (deferred/let-flow
      [resp (http/request request-map)]
      resp)))

@(request-example
   {:method            :get
    :url               "https://httpstat.us/200"
    :request-timeout   1000
    :throw-exceptions? false})
```

**Comment by Hamled** [comment]
I've noticed this as well. On the aleph website there are [examples for a TCP server](https://aleph.io/aleph/literate.html) which include equivalent implementations using `chain` and `let-flow`, both in a `loop` form (search for `slow-echo-handler`).

The implementation using `chain` works as indicated by the example code, but the implementation with `let-flow` blocks forever on taking a message from the client stream.

**Comment by theronic** [comment]
Same here - I've spent about 3 hours trying to figure out what i'm doing wrong, but it indeed seems to be let-flow that blocks.

Using `d/chain` with `d/loop` and `d/recur` works, however.

**Comment by ztellman** [comment]
I'm sorry for the very slow reply on this, as you may have noticed my maintenance on all of my Clojure projects isn't very active these days.  This is a pretty egregious one, though, since `loop` and `let-flow` are meant to be freely composable.  The issue was that `let-flow` does analysis on the lexical scope outside of the `let-flow` form, and was incorrectly blocking on the `deferred` that `loop` had created to represent its eventual value, causing a deadlock.  I'll cut a new release so that the fix can be used, and will continue to chip away at the backlog of issues, with an eye towards creating 1.0 releases for both Aleph and Manifold.

**Comment by theronic** [comment]
Thanks, @ztellman! That fixes it.

Have submitted [a PR](https://github.com/aleph-io/manifold/pull/191) to include a deps.edn in Manifold to refer to a specific commit. Until a new release is deployed to Clojars, those who want to use this immediately without building locally, can temporarily refer to my fork in deps.edn:

```
aleph/manifold    {:git/url    "https://github.com/theronic/manifold.git"
                   :sha        "aec26d90c4c0eeb71394c416821d0c5fe8bb1fc9"}
```

**Comment by ztellman** [comment]
I pushed 0.1.9-alpha4, which has this change.
